# This is a workflow to run unittests after every push

name: unittests

on:
  push:
    branches: [ ]
  pull_request:
    branches: [ ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 17
          
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/build.gradle.kts') }}
          restore-keys: ${{ runner.os }}-m2
          
      - name: Run tests with Gradle
        run: ./gradlew test
